[main-sg-classic] Install build binaries based on package definition
See merge request search-guard/search-guard-kibana-plugin!924

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -14,7 +14,7 @@ variables:
   SG_SF_PLUGIN_RELEASE_REPO: search-guard-kibana-plugin-release
   SG_SF_PLUGIN_NAME: search-guard-kibana-plugin
   SG_SB_PLUGIN_NAME: search-guard-suite-plugin
-  NODE_VERSION: 16.13.0
+  NODE_DOCKER: node:21.6.1
 
 image: circleci/openjdk:${SG_JAVA_BUILD_VERSION}-jdk-browsers
 
@@ -44,6 +44,7 @@ before_script:
     echo "================================="
 
 stages:
+  - prepare
   - build
   - "Unit Tests"
   - package
@@ -52,9 +53,31 @@ stages:
   - "Frontend Int Tests External Features"
   - release
 
+prepare_versions:
+  stage: prepare
+  tags:
+    - build  
+  script:
+     - |
+       set -e
+       URL="https://raw.githubusercontent.com/$SB_PRODUCT/$SF_PRODUCT/v$SF_VERSION/package.json"
+       curl -s $URL -o .build_versions
+       if [ ! -f package.json ]; then
+          echo "Failed to download package.json from $URL"
+          exit 1
+       fi  
+       echo "KIBANA_BUILD_NODE_VERSION=$(jq -r '.engines.node | gsub("^\\^"; "")' .build_versions)" > versions.env
+       echo "KIBANA_BUILD_YARN_VERSION=$(jq -r '.engines.yarn | gsub("^\\^"; "")' .build_versions)" >> versions.env
+       cat versions.env
+  artifacts:
+    paths:
+      - versions.env
+
+
+
 #This case is for usual commit to the branch, doing only unit testing and local build
 build:
-  image: node:current
+  image: $NODE_DOCKER
   stage: build
   tags:
     - build
@@ -65,6 +88,7 @@ build:
   script:
     - |
       set -e
+      source versions.env
       source ci/install_dependencies.sh
       source ci/init_build.sh
       cd $SF_REPO_DIR/plugins/search-guard
@@ -97,7 +121,7 @@ build:
 
 #This case is for release tag commit to the branch, doing only unit testing and local build
 build_release:
-  image: node:current
+  image: $NODE_DOCKER
   stage: build
   rules:
     - if: '$CI_COMMIT_TAG =~ /^sg-.*/'
@@ -108,6 +132,7 @@ build_release:
       set -e
       sed -i -e "s#\"version\":.*\"#\"version\": \"$SF_VERSION\"#" $SF_JSON
       sed -i -e "s#\"version\":.*\"#\"version\": \"$BUILD_VERSION\"#" package.json
+      source versions.env
       source ci/install_dependencies.sh
       source ci/init_build.sh
       cd $SF_REPO_DIR/plugins/search-guard
@@ -130,7 +155,7 @@ build_release:
     expire_in: 24h
 
 unit_tests:
-  image: node:current
+  image: $NODE_DOCKER
   stage: "Unit Tests"
   interruptible: true
   rules:
@@ -138,10 +163,11 @@ unit_tests:
       when: never
     - when: always
   tags:
-    - build
+    - test
   script:
     - |
       set -e
+      source versions.env
       source ci/install_dependencies.sh
       source ci/init_build.sh
       start_section tests "Unit Tests"
